//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QECWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        [Key]
        public int id { get; set; }

        [Display(Name = "User Name")]
        [Required(ErrorMessage = "required")]
        public string username { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "required")]
        [DataType(DataType.Password)]
        public string password { get; set; }
    }
}
